# Generated by Django 2.1.7 on 2019-03-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Fullstack',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Openstack',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Pytest',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Teststack',
            fields=[
            ],
        ),
    ]
