# Generated by Django 2.1.7 on 2019-03-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_database', '0002_auto_20190324_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Fullstack',
            fields=[
            ],
        ),
    ]
