# Generated by Django 2.1.7 on 2019-03-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_database', '0003_employee_fullstack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Openstack',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Pytest',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Teststack',
            fields=[
            ],
        ),
    ]
